/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.datatorrent.stram.extensions.api;

import org.apache.hadoop.service.Service;

import com.datatorrent.stram.StramAppContext;
import com.datatorrent.stram.StreamingContainerManager;
import com.datatorrent.stram.api.StramEvent;
import com.datatorrent.stram.api.StreamingContainerUmbilicalProtocol.ContainerHeartbeat;

public interface ApexService extends Service
{
  /**
   * Some plugin might require direct access to engine's internal
   * structure.
   * @param context
   */
  void setAppContext(StramAppContext context);

  /**
   * Access to the engine internal details, from this plugin could
   * access virtually any part of the application. In future, we
   * could create an internal to expose only specific part of the
   * engine.
   *
   * @param manager
   */
  void setDagManager(StreamingContainerManager manager);

  /**
   * Examine the heartbeat request from the StramChild
   * this request contains stats, so plugin can maintain its
   * own stats if required.
   * @param heartbeat
   */
  void handleHeartbeat(ContainerHeartbeat heartbeat);

  /**
   * Call periodically, the difference between two invocation
   * not gaurented to be same. and is approximately equal to 1s.
   */
  void tick();

  /**
   * Handle event generated by the Stram.
   * @param event
   */
  void handleEvent(StramEvent event);
}
